name: CI

on:
  pull_request:
  push:
    branches:
      - main
      
permissions:
  contents: write

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
  
        - name: Set up bun
          uses: oven-sh/setup-bun@v1
          with:
            bun-version: latest
  
        - name: Install dependencies
          run: 
            bun install -D tailwindcss
            bun install -D prettier-plugin-tailwindcss
  
        - name: Build Tailwind CSS
          run: bunx tailwindcss -i ./src/input.css -o ./public/tailwind.css

    deploy:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./public